
INSERT INTO categories (category_name) VALUES
	(N'Nam'),
	(N'Nữ'),
	('Unisex'),
	('Mini'),
	('Niche');

INSERT INTO suppliers (supplier_name, address, phone_number) VALUES
	('Bvlgari Fragrance Supply Co.', N'93 Đinh Tiên Hoàng, Quận 1, TP. Hồ Chí Minh', '0901234567'),
	('Yves Saint Laurent Distributors', N'45 Lý Tự Trọng, Quận 1, TP. Hồ Chí Minh', '0912345678'),
	('Chanel Perfume Partners', N'88 Đồng Khởi, Quận 1, TP. Hồ Chí Minh', '0923456789'),
	('Dior Fragrance Distributors', N'26 Lê Lợi, Quận 1, TP. Hồ Chí Minh', '0934567890'),
	('Kilian Haute Parfum', N'6 Thái Văn Lung, Quận 1, TP. Hồ Chí Minh', '0945678901'),
	('Versace Fragrance Enterprises', N'45 Lý Tự Trọng, Quận 1, TP. Hồ Chí Minh', '0956789012'),
	('Jean Paul Gaultier Fragrance Solutions', N'92 Hai Bà Trưng, Quận 1, TP. Hồ Chí Minh', '0967890123'),
	('Tom Ford Premium Fragrance', N'31 Lê Duẩn, Quận 1, TP. Hồ Chí Minh', '0978901234');

INSERT INTO brands (brand_name) VALUES
	('BVLGARI'),
	('Yves Saint Laurent'),
	('Chanel'),
	('Dior'),
	('Kilian'),
	('Versace'),
	('Jean Paul Gaultier'),
	('Tom Ford');

INSERT INTO products (product_name, categoryid, supplierid, brandid, price, description, imageurl, stock_quantity) VALUES
    ('Bvlgari Aqva Pour Homme', 1, 1, 1, 2450000, N'Mang đến cảm giác như đắm mình trong làn nước biển trong lành, Aqva Pour Homme mở đầu với hương cam bergamot và quả cam quýt Sicily. Lớp hương giữa đưa bạn vào thế giới biển cả với rong biển Posidonia và hoa lavender, kết thúc bằng hương gỗ hổ phách và xạ hương ấm áp, gợi lên hình ảnh một người đàn ông mạnh mẽ nhưng tràn đầy sức sống.', 'https://product.hstatic.net/1000340570/product/bvlgari-aqva-pour-homme-100ml_a809dabd88c246088c256ff0f18658cb_master.jpg', 15),

    ('Yves Saint Laurent Mon Paris', 2, 2, 2, 2950000, N'Mon Paris là sự kết hợp tinh tế giữa các hương hoa và trái cây, mang đến cảm giác ngọt ngào và say đắm. Hương đầu mở ra với sự tươi mát của quả dâu tây, quả mâm xôi, quả lê và cam bergamot. Tiếp đến là hương giữa với sự hòa quyện của hoa nhài Sambac, hoa cam, hoa cà độc dược và hoa mẫu đơn trắng. Cuối cùng, hương cuối để lại dấu ấn ấm áp của hoắc hương Indonesia, xạ hương trắng và gỗ tuyết tùng. Mon Paris được thiết kế để phản ánh niềm đam mê mãnh liệt và tình yêu nồng cháy, giống như một cuộc hành trình khó quên ở Paris. Thiết kế chai nước hoa với màu hồng nhạt và chiếc nơ đen tinh tế cũng góp phần tôn lên vẻ sang trọng và thanh lịch của sản phẩm.', 'https://product.hstatic.net/1000340570/product/yves-saint-laurent-mon-paris-90ml-edp_b942bd34a30e4d029b6218e811cc57ed_master.jpg', 30),

    ('Chanel Chance Eau Tendre', 2, 3, 3, 3800000, N'Chance Eau Tendre là một hương thơm nữ tính, tươi mát và đầy tinh tế, ra mắt vào năm 2010. Hương đầu mở ra với sự tươi mát của quả bưởi và mộc qua, mang lại cảm giác sảng khoái và tràn đầy năng lượng. Tiếp đến là hương giữa với sự hòa quyện của hoa nhài và lan dạ hương, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn êm dịu và đẫy đà của xạ hương, hoa diên vĩ và gỗ tuyết tùng Virginia, mang lại cảm giác thanh lịch và tinh tế. Chance Eau Tendre là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa nhẹ nhàng, vừa quyến rũ, lý tưởng cho những ngày hè vô tư hoặc các dịp đặc biệt.', 'https://product.hstatic.net/1000340570/product/chanel-chance-eau-tendre-eau-de-toilette-50ml_e108c312d4854ff88fe537f4360993c3_master.jpg', 50),

    ('Dior Miss Dior Blooming Bouquet', 2, 4, 4, 2500000, N'Dior Miss Dior Blooming Bouquet là một hương thơm tươi mát và dịu dàng, như một bó hoa mới nở. Hương thơm mở đầu với sự tươi mát của cam bergamot, mang lại cảm giác sảng khoái và đầy năng lượng. Tiếp đến là sự kết hợp tinh tế của hoa hồng Damascus và hoa mẫu đơn, tạo nên một lớp hương giữa ngọt ngào và quyến rũ. Cuối cùng, xạ hương trắng mang lại sự mềm mại và ấm áp, để lại một dấu ấn nhẹ nhàng và thanh lịch trên da. Đây là một mùi hương thanh lịch và nữ tính, hoàn hảo cho những ai yêu thích sự tươi mới và quyến rũ.', 'https://product.hstatic.net/1000340570/product/dior-miss-dior-blooming-bouquet_5859c56197694d518431954615a3d6f4_master.jpg', 40),

    ('Kilian Black Phantom', 1, 5, 5, 7350000, N'Kilian Black Phantom - "Memento Mori" là một hương nước hoa bí ẩn và quyến rũ. Mở đầu với rượu rum Caribbean và cà phê đậm đà, hương thơm này mang đến cảm giác nguy hiểm và lôi cuốn. Tầng hương giữa là cacao và whisky ngọt ngào, kết thúc với gỗ đàn hương và vetiver sâu lắng. Đây là lựa chọn hoàn hảo cho những ai yêu thích sự bí ẩn và muốn để lại ấn tượng khó quên.', 'https://product.hstatic.net/1000340570/product/kilian-black-phantom-memento-mori_45baadc56dd147599df3860c9b80e852_master.jpg', 13),

    ('Versace Dylan Blue', 1, 6, 6, 2420000, N'Versace Dylan Blue là một hương nước hoa nam tính, mạnh mẽ với sự kết hợp của hương cam bergamot, bưởi và lá vả, mang đến cảm giác tươi mát và sắc nét của vùng Địa Trung Hải. Hương giữa là sự pha trộn của lá violet và hương gỗ, tạo nên sự ấm áp và nam tính. Cuối cùng, hương hoắc hương và xạ hương mang đến sự bền lâu và quyến rũ. Chai nước hoa được thiết kế với màu xanh dương đậm và các chi tiết vàng, gợi nhớ đến biển Địa Trung Hải và văn hóa Hy Lạp - La Mã.', 'https://product.hstatic.net/1000340570/product/dylan-blue_919771324a4b46998825d6dfbdc5764f_master.jpg', 50),

    ('Jean Paul Gaultier Classique Pin-up', 2, 7, 7, 2600000, N'Jean Paul Gaultier Classique Pin-Up là một hương thơm đầy quyến rũ và nữ tính, ra mắt vào năm 2020. Hương thơm mở đầu với sự tươi mát, sảng khoái của gừng và chanh, mang lại cảm giác năng động và tràn đầy sức sống. Tiếp đến là sự ngọt ngào, quyến rũ của hoa cam và kẹo dẻo, tạo nên một lớp hương giữa đầy mê hoặc. Cuối cùng, hương vanilla và hổ phách kết hợp hoàn hảo, để lại một dấu ấn ấm áp và gợi cảm trên da. Classique Pin-Up không chỉ là một mùi hương, mà còn là một tuyên ngôn về sự tự tin và phong cách.', 'https://product.hstatic.net/1000340570/product/jean_paul_gaultier_classique_pin_up_c02dcc3fa3e14b3e9b381be1a0b53625_master.jpg', 20),

    ('Versace Crystal Noir', 2, 6, 6, 2442000, N'Versace Crystal Noir là một hương nước hoa nữ tính, quyến rũ với sự kết hợp của hương bạch đậu khấu, gừng và tiêu. Hương giữa là sự hòa quyện của hoa nhài, hoa huệ và hoa cam, tạo nên sự ngọt ngào và nữ tính. Cuối cùng, hương gỗ đàn hương và xạ hương mang đến sự ấm áp và bền lâu. Crystal Noir được mô tả là một hương thơm huyền bí và gợi cảm, thích hợp cho những buổi tối lãng mạn hoặc các sự kiện đặc biệt.', 'https://product.hstatic.net/1000340570/product/versace-crystal-noir-edt_2a522575d57449a883defc16e0d116ac_master.jpg', 25),

    ('Chanel Allure Homme Sport Eau Extreme', 1, 3, 3, 3650000, N'Allure Homme Sport mang đến một hương thơm tươi mát và năng động. Hương đầu là sự kết hợp của cam, quýt và aldehyde, mang lại cảm giác sảng khoái. Hương giữa là sự hòa quyện của tiêu đen, hoa cam và dầu neroli. Hương cuối là sự ấm áp của đậu tonka, hổ phách và xạ hương trắng. Đây là một mùi hương lý tưởng cho những người đàn ông yêu thích thể thao và các hoạt động ngoài trời.', 'https://product.hstatic.net/1000340570/product/chanel-allure-homme-sport-eau-de-toilette-100ml_b346b3a4de84438bb866718bb8711d2c_master.jpg', 60),

('Dior Hypnotic Poison Eau de Toilette', 2, 4, 4, 2500000, N'Một hương thơm ngọt ngào và gợi cảm với hương đầu của cam bergamot và mận, hương giữa của hoa nhài và hoa cam, và hương cuối của vani và xạ hương. Hypnotic Poison mang lại cảm giác bí ẩn và quyến rũ, lý tưởng cho buổi tối. Hương thơm này còn có sự kết hợp của các nốt hương hổ phách và vani, tạo nên một mùi hương ấm áp và ngọt ngào.', 'https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-ltdcvvpj6404d1.webp', 40),

('Bvlgari Goldea Eau de Parfum', 2, 1, 1, 3600000, N'Bvlgari Goldea Eau de Parfum là một hương thơm nữ tính đầy quyến rũ, tôn vinh ánh sáng vàng rực rỡ và sự sang trọng vĩnh cửu. Hương đầu mở ra với sự tươi mát của cam Bergamot, cam ngọt và xạ hương vàng lấp lánh. Tầng hương giữa gợi cảm với hoa nhài, ylang-ylang và xạ hương mịn màng, tạo nên sự thanh thoát và quyến rũ. Hương cuối đậm đà với nhựa hổ phách, hoắc hương và xạ hương trắng, mang lại cảm giác ấm áp và lưu luyến lâu dài.
Thiết kế chai lấy cảm hứng từ ánh vàng, kết hợp đường cong mềm mại, thể hiện sự nữ tính và quyền lực, là biểu tượng hoàn hảo cho vẻ đẹp vượt thời gian. Goldea phù hợp cho những dịp đặc biệt, khi bạn muốn tỏa sáng với sự tự tin và phong cách riêng.', 'https://product.hstatic.net/1000340570/product/bvlgari-goldea-eau-de-parfum-90ml_fc6cdf1799544a66a96caf2b9f79a762_master.jpg', 25),

    ('Yves Saint Laurent Kouros', 1, 2, 2, 2990000, N'Kouros là một mùi hương mạnh mẽ và đầy nam tính, thể hiện tinh thần chiến thắng và sự chinh phục. Hương đầu mở ra với sự tươi mát của aldehydes, cam bergamot, ngải thơm và ngò rí. Tiếp đến là hương giữa với sự hòa quyện của hoa cẩm chướng, cỏ hương bài, hoắc hương, quế, hoa nhài, rễ cây diên vĩ và phong lữ. Cuối cùng, hương cuối để lại dấu ấn ấm áp của rêu sồi, hổ phách, nhang, mật ong, da thuộc, cầy hương, xạ hương, đậu tonka và vani. Kouros mang đến một mùi hương fougère da thuộc, với sự kết hợp độc đáo giữa các thành phần tạo nên một dấu ấn khó quên. Hương thơm này vừa sạch sẽ, vừa mạnh mẽ, thể hiện sự nam tính và quyến rũ.', 'https://hdperfume.vn/cdn/shop/products/b.png?format=webp&v=1669368303&width=910', 40),

    ('Tom Ford Noir Extreme', 1, 8, 8, 3800000, N'Tom Ford Noir Extreme là một hương nước hoa nam tính, mạnh mẽ với sự kết hợp của các hương liệu ấm áp và gợi cảm. Hương đầu mở ra với sự pha trộn của bạch đậu khấu, nhục đậu khấu, nghệ tây và cam mandarin, mang đến cảm giác tươi mới và đầy sức sống. Hương giữa là sự hòa quyện của hoa hồng, hoa nhài và hoa cam, tạo nên một tầng hương ngọt ngào và quyến rũ. Cuối cùng, hương gỗ đàn hương, hổ phách và vani mang đến sự ấm áp và bền lâu, để lại một dấu ấn mạnh mẽ và nam tính.', 'https://orchard.vn/wp-content/uploads/2024/07/tom-ford-noir-extreme-edp_3.jpg', 30),

    ('Chanel Coco Eau de Toilette', 2, 3, 3, 3050000, N'Chanel Coco Eau de Toilette là một hương thơm nữ tính, ra mắt vào đầu những năm 1980, mang đến sự kết hợp tuyệt hảo giữa cá tính mạnh mẽ và phong cách baroque của Gabrielle Chanel. Hương đầu mở ra với sự tươi mát của cam quýt và ngò thơm. Tiếp đến là hương giữa với sự hòa quyện của hoa nhài, hoa cam và hoàng lan, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn ấm áp của vani, đậu tonka, hoắc hương và hổ phách, mang lại cảm giác sang trọng và bí ẩn12. Đây là một mùi hương lý tưởng cho những người phụ nữ yêu thích sự thanh lịch và quyến rũ.', 'https://product.hstatic.net/1000340570/product/chanel-coco-eau-de-toilette_a621a91cdae54dd4837cec6677a67730_master.jpg', 30),
    
    ('Dior Sauvage Eau de Parfum', 1, 4, 4, 3800000, N'Một hương thơm tươi mát và mạnh mẽ với hương đầu của cam bergamot, hương giữa của tiêu và hương cuối của ambroxan. Đây là một mùi hương nam tính và cuốn hút, lý tưởng cho cả ngày và đêm. Sauvage mang lại cảm giác tự do và hoang dã, như một làn gió mới từ thiên nhiên. Hương thơm này được lấy cảm hứng từ những không gian rộng lớn và bầu trời xanh thẳm.', 'https://product.hstatic.net/1000340570/product/dior-sauvage-eau-de-parfum-100ml_e1c611f46daa451f8a159c1652c8d6c1_master.jpg', 25),

('Chanel Bleu de Chanel Eau de Parfum', 1, 3, 3, 3500000, N'Chanel Bleu de Chanel Eau de Parfum là một hương thơm nam tính, mạnh mẽ và cuốn hút, ra mắt vào năm 2010. Hương đầu tươi mát với cam bergamot, chanh và bạc hà. Hương giữa hòa quyện gừng, nhục đậu khấu và hoa nhài, tạo nên sự nam tính và lôi cuốn. Hương cuối ấm áp với gỗ đàn hương, hoắc hương và nhựa hương, mang lại cảm giác sâu lắng và quyến rũ. Đây là mùi hương lý tưởng cho người đàn ông hiện đại, tự tin và quyết đoán.', 'https://product.hstatic.net/1000340570/product/chanel-bleu-de-chanel-eau-de-parfum-100ml_d94a8cd0feb743b59a4e612a651b7390_master.jpg', 30),

    ('Versace Eros', 1, 6, 6, 2590000, N'Versace Eros là một hương nước hoa nam tính, mạnh mẽ với sự kết hợp của hương bạc hà, táo xanh và chanh Ý. Hương giữa là sự pha trộn của đậu tonka, hoa phong lữ và ambroxan, tạo nên sự ấm áp và gợi cảm. Cuối cùng, hương vani, rêu sồi và gỗ tuyết tùng mang đến sự bền lâu và quyến rũ. Chai nước hoa màu xanh dương đậm với biểu tượng Medusa và họa tiết Hy Lạp cổ điển, thể hiện sự mạnh mẽ và quyền lực của thần Eros.', 'https://product.hstatic.net/1000340570/product/versace-eros-for-men_e21f596ba1f6467eb39ace8813943882_master.jpg', 22),

    ('Tom Ford Black Orchid', 2, 8, 8, 4000000, N'Tom Ford Black Orchid là một hương nước hoa sang trọng và quyến rũ, nổi bật với sự kết hợp của các thành phần độc đáo. Hương đầu mở ra với sự pha trộn của nấm cục đen, ylang-ylang và cam bergamot, mang đến cảm giác bí ẩn và lôi cuốn. Hương giữa là sự hòa quyện của mận đen ngâm rượu rum và hoa lan đen, tạo nên một tầng hương đầy gợi cảm và quyến rũ. Cuối cùng, hương gỗ đàn hương, hoắc hương và vani mang đến sự ấm áp và bền lâu, để lại một dấu ấn khó quên trên da.', 'https://product.hstatic.net/1000340570/product/tom-ford-black-orchid_4af20be652c44080819ea9e7115f7852_master.jpg', 15),

	('Tom Ford Lost Cherry', 3, 8, 8, 7200000, N'Tom Ford Lost Cherry là một hương nước hoa ngọt ngào và gợi cảm, nổi bật với sự kết hợp của các thành phần trái cây và hoa cỏ. Hương đầu mở ra với sự pha trộn của anh đào đen và hạnh nhân đắng, mang đến cảm giác ngọt ngào và lôi cuốn. Hương giữa là sự hòa quyện của hoa hồng Thổ Nhĩ Kỳ và hoa nhài sambac, tạo nên một tầng hương đầy gợi cảm và quyến rũ. Cuối cùng, hương gỗ đàn hương, cỏ hương bài và tuyết tùng mang đến sự ấm áp và bền lâu, để lại một dấu ấn khó quên trên da.', 'https://product.hstatic.net/1000340570/product/tom-ford-lost-cherry-edp-100ml_0fa8a03b56ce4cbc88a4cb60aa8ef509_master.jpg', 18),


('BVLGARI Man Wood Essence', 1, 1, 1, 3360000, N'Hương thơm này là một chuyến du hành vào thiên nhiên sâu thẳm. Mở đầu với sự tươi mát của cam quýt, điểm xuyết chút vị ngọt của quả chanh vàng Ý, nhanh chóng chuyển sang tầng hương chính là sự ấm áp từ gỗ tuyết tùng, hương hoắc hương nồng nàn và cỏ hương bài tinh tế. Đây là sự lựa chọn hoàn hảo cho người đàn ông mạnh mẽ, hòa mình với thiên nhiên nhưng vẫn giữ được nét hiện đại đầy tự tin.', 'https://product.hstatic.net/1000340570/product/bvlgari-man-wood-essence-eau-de-parfum-100ml_07560f7a2d2a40b8aae5266b6084d70f_master.jpg', 24),

('BVLGARI Man in Black', 1, 1, 1, 3360000, N'Man in Black được hãng BVL tuyên bố là một mùi hương Nam tính, táo bạo và  lôi cuốn. Mở đầu mùi hương bằng việc mix Gia vị, thuốc lá và Rượu Rum có lẽ là một cách thức táo bạo nhất mà chuyên gia nước hoa Alberto Morillas đã từng làm, đó là sự nam tính, trầm tĩnh, như thể định nghĩa nó là một mùi hương hoàn toàn danh cho "phái mạnh" vậy. Da thuộc cùng sự nhẹ nhàng của Hoa diễn vĩ nằm ở hương giữa, tạo khoảng không gian nhẹ nhàng, thư thái, trước khi kết thúc bằng hương Gỗ Guaiac và Đậu tonka. Bvlgari Man In Black là một người đàn ông điển hình cho sự trưởng thành, thành đạt và hấp dẫn, mang trong mình nhiều suy nghĩ của một kẻ đầy tham vọng, dám nghĩ, dám làm.', 'https://product.hstatic.net/1000340570/product/bvlgari-man-in-black-eau-de-parfum-100ml_488efd0da50f4c7ea7f50bc68724baa2_master.jpg', 20),

('BVLGARI Man Extreme', 1, 1, 1, 2000000, N'Là bức tranh miêu tả sức hút khó cưỡng của người đàn ông hiện đại luôn đuổi theo sự mới mẻ, người đàn ông luôn thích thú trước những đổi thay của vạn vật. Man Extreme mở đầu bằng hương bưởi và chanh mát lạnh, kết hợp với hương thơm gợi cảm từ hoa lan nam phi. Lớp nền là xạ hương và hổ phách, tạo nên cảm giác mạnh mẽ và đầy nam tính.', 'https://product.hstatic.net/1000340570/product/bvlgari-man-extreme-100ml_a259d1d9902149448b3e727746b471ce_master.jpg', 30),

('Bvlgari Man Glacial Essence', 1, 1, 1, 3360000, N'Một hương thơm có độ tương phản cao là một luồng không khí lạnh giá, giải phóng cho mọi người đàn ông đang sở hữu nó trên làn da. Bvlgari Man Glacial Essence thể hiện sự nam tính không thể cưỡng lại của một người đàn ông trong hành trình tìm kiếm sự vĩ đại không ngừng. Sự tươi mát của lớp hương đầu lấp lánh, đánh thức tầng hương giữa của gỗ gỗ cùng sức sống bất ngờ, lên đến đỉnh điểm là âm sắc mãnh liệt và đầy tham vọng của lớp hương khô kết tinh.', 'https://product.hstatic.net/1000340570/product/bvlgari-man-glacial-essence_fbb926673dd642f5ba755717a11232bf_master.jpg', 20),

('Bvlgari Omnia Crystalline', 2, 1, 1, 2250000, N'Mở ra với nét chân thật, xanh ngắt của Trúc và ngọt mát của Lê, Omnia Crystalline đem lại cảm giác mới mẻ, như được tái sinh thêm một lần nữa với sự kết hợp tinh tế này. Không dừng lại ở đó, những nốt hương thuần khiết của Hoa sen, thanh đậm của Trà cùng sự tươi tắn như những thiếu nữ mới lớn của Cassia đã vẽ lên nét nữ tính, mềm dịu vốn có của Omnia Crystalline.
Khởi đầu bằng sự tươi mát, dịu dàng từ hoa và lá, Omnia Crystalline kết thúc một ngày của mình bằng sự tao nhã, thanh lịch của mình với các tông hương được yêu thích đặc biệt như Xạ hương, Gỗ sồi và Gỗ Guaiac.', 'https://product.hstatic.net/1000340570/product/trang_297e0f437cda4cd8a8f01029399c889f_master.jpg', 25),

('Bvlgari Omnia Amethyste', 2, 1, 1, 2250000, N'Với chỉ làn hương đầu tiên, Omnia Amethyste đã thổi một làn gió tươi mát từ Bưởi hồng cùng sự hòa quyện giữa lá trà tươi và cỏ non, đem lại cho người dùng cảm giác sảng khoái, dễ chịu khó tả. Bao quát cả một tầng hương tiếp theo bằng khu vườn của sự thanh lịch với Hoa diên vĩ và hoa Hồng Bulgaria, sẽ là bất khả để cưỡng lại hương phấn hoa đặc trưng với mùi hương quyến rũ, gọi mời này. Cuối cùng, để lưu giữ lại hành trình xuyên qua từng làn hương, từng nốt Hương gỗ và Hoa vòi voi nhẹ nhàng được khám phá, để lại cho ta cảm giác ấm áp hơn nhưng vẫn tràn ngập hương hoa ngọt ngào ban đầu. Một sự trọn vẹn đến khó tin.', 'https://product.hstatic.net/1000340570/product/tim_9af2c5b945694af0b03485bda57ccf62_master.jpg', 25),

('Bvlgari Rose Goldea', 2, 1, 1, 2900000, N'Khi bắt đầu mở ra màn trình diễn của mình, Rose Goldea đã khiến bất kỳ ai đối diện cũng phải thấy quyến luyến và gần gũi nơi da thịt bởi chất xúc tác mãnh liệt của Xạ hương. Ấy thế, Rose Goldea của chúng ta vẫn không hề thiếu đi sự thuỳ mị và dịu dàng với Lựu và Cam bergamot. Và kể cả khi bạn có ngày một dấn thân sâu hơn vào sức hút của mùi hương này, lúc bấy giờ đã trở nên phương phi đến kịch liệt với các nốt hương hoa nâng đỡ như Mẫu đơn hay Nhài, thì yên tâm nhé, Rose Goldea vẫn luôn biết cách chiều lòng người và nịnh khứu giác. Điểm xuyết với chút ngọt ấm, hơi tư lự của Đàn hương và Vanilla, Rose Goldea cuối cùng cũng đã hoàn thành bức tự họa tinh tế khó cưỡng của mình.', 'https://product.hstatic.net/1000340570/product/bvlgari-rose-goldea_75e4478bf558467ea17dfa264f0363a2_master.jpg', 25),

('Bvlgari Splendida Tubereuse Mystique', 2, 1, 1, 3800000, N'Mở đầu với hương thơm ấn tượng, ngọt ngào thanh lịch của Nho đen và Davana. Tuy nhiên, note hương đầu tiên sẽ qua nhanh để nhường chỗ cho Hoa huệ bừng lên một sự quyến rũ và thu hút ngay tầng hương giữa này. Dần về sau được kết thúc bởi hương từ Vanilla và Mộc dược, nốt hương ngọt ngào hoà quyện giữa sự tinh tế và sang trọng càng tăng thêm chiều sâu cho chính chai nước hoa vốn dĩ là một điều gì đó rất bí ẩn và cuốn hút này. Đây là hương nước hoa dành cho phái đẹp mang mùi hương quyến rũ, nồng nàn, sang trọng và cũng là hương thơm giúp chị em tự tin hơn trong công việc, tình yêu và cuộc sống.', 'https://product.hstatic.net/1000340570/product/bvlgari-splendida-tubereuse-mystique-eau-de-parfum-100ml_87e27459a19b4cd08f7e94aa509be343_master.jpg', 18),

('Bvlgari Eau Parfumée au Thé Vert', 3, 1, 1, 3200000, N'Hương đầu của Eau Parfumee au The Vert Bvlgari tỏa hương tươi mát với sự kết hợp hoàn hảo của rau mùi tươi, hoa cam tươi tắn và vị chua ngọt của quýt. Cùng với cam bergamot, bạch đậu khấu và chanh, hương đầu mang đến một cảm giác tươi mới và bừng sáng, như là những giọt sương mai đọng trên tán lá xanh mướt.
Hương giữa của nước hoa này là một vườn hoa thơm ngát với hoa nhài tinh tế, hoa lily thung lũng thanh tao và hoa hồng Bulgari quyến rũ. Sự hòa quyện của những hương hoa này tạo nên một không gian thơm ngát và lãng mạn, như một khu vườn hoa tràn đầy nắng và gió.
Hương cuối của Bvlgari Eau Parfumee au The Vert mang đến một cảm giác ấm áp và lôi cuốn với gỗ đàn hương tao nhã, hổ phách tinh tế và xạ hương quyến rũ. Sự kết hợp này tạo nên một dư vị đặc trưng và độc đáo, kéo dài một cách lâu dài trên da. Bên cạnh đó, gỗ quý và gỗ tuyết tùng còn tăng thêm sự sang trọng và quý phái cho hương thơm cuối cùng.', 'https://admin.xixonshop.net/wp-content/uploads/2023/05/nuoc-hoa-bvlgari-eau-parfumee-au-the-vert-1.jpg', 30),

('Bvlgari Eau Parfumée au Thé Blanc', 3, 1, 1, 3200000, N'Hương đầu của Bvlgari Eau Parfumee Au The Blanc mang đến một cảm giác tươi mát và thanh khiết với hương trà tinh tế, sự hòa quyện của artemisia, cam bergamot và hoa cam tươi tắn. Cùng với một chút cam đắng, hương đầu mang đến nét phá cách và tinh tế, tựa như những cánh hoa mở ra trong buổi sáng mời gọi.
Hương giữa của nước hoa này kết hợp sự ấn tượng của tiêu tươi, thảo quả tinh tế và rau mùi tươi mát. Sự hòa quyện của những hương thơm này tạo nên một cảm giác tươi mới và bắt mắt, như một khu vườn xanh mát tràn đầy sự sống.
Hương cuối của Bvlgari Eau Parfumee au The Blanc là sự kết hợp độc đáo của hổ phách tinh tế, xạ hương quyến rũ và hoa hồng quyến rũ. Sự giao thoa của hoa nhài tinh tế và gỗ ấm áp tạo nên một dư vị cuối cùng đầy lôi cuốn, đọng mãi trên da. Hương cuối mang đến sự độc đáo và tinh tế, mang lại một sự cuốn hút và quý phái.', 'https://admin.xixonshop.net/wp-content/uploads/2023/05/nuoc-hoa-bvlgari-eau-parfumee-au-the-blanc-1.jpg', 30),

('Bvlgari Eau Parfumée au Thé Noir', 3, 1, 1, 25500000, N'Bvlgari Eau Parfumée au Thé Noir là mùi hương unisex sang trọng, lấy cảm hứng từ trà đen ấm áp và bí ẩn. Nốt hương mở đầu tươi mát từ cam Bergamot và hoa hồng dẫn lối đến tầng giữa trầm ấm của trà đen và hoa mộc lan. Tầng cuối gợi cảm với nhựa benzoin và gỗ đàn hương, tạo cảm giác tinh tế và quyến rũ. Với thiết kế chai màu đen mờ sang trọng, đây là lựa chọn lý tưởng cho những ai yêu thích sự thanh lịch và chiều sâu, phù hợp trong mùa thu đông hoặc các dịp đặc biệt.', 'https://product.hstatic.net/200000201387/product/10_0dd5220ddce74b429743b74ac203d8cb_master.jpg', 30),

('Bvlgari Eau Parfumée au Thé Rouge', 3, 1, 1, 2580000, N'Eau Parfumée au Thé Rouge là một hương thơm tinh tế và nhẹ nhàng, lấy cảm hứng từ trà đỏ Rooibos Nam Phi. Với sự mở đầu tươi mới của cam đỏ và hồng tiêu, hòa quyện cùng trà Yunnan và xạ hương trong nền ấm áp, nước hoa này mang đến cảm giác thư giãn và thanh lịch, phù hợp cho cả nam lẫn nữ, lý tưởng để sử dụng hàng ngày.', 'https://nuochoa.vn/wp-content/uploads/2022/10/nuoc-hoa-bvlgari-eau-parfumee-au-the-rouge-nam.jpg', 30),

('BVLGARI Omnia Crystalline Eau de Toilette Mini', 4, 1, 1, 400000, N'BVLGARI Omnia Crystalline Eau de Toilette Mini có hương thơm tươi mát và tinh tế, lấy cảm hứng từ sự trong suốt của pha lê. Hương đầu mở ra với sự tươi mát của quả lê và tre, mang lại cảm giác mới mẻ và sảng khoái. Tiếp đến là hương giữa với sự hòa quyện của hoa sen và trà trắng, tạo nên một tầng hương nhẹ nhàng và thanh khiết. Cuối cùng, hương cuối để lại dấu ấn ấm áp của xạ hương và gỗ guaiac, mang lại cảm giác thanh lịch và tinh tế. Omnia Crystalline là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa nhẹ nhàng, vừa quyến rũ, lý tưởng cho những ngày hè nhẹ nhàng và thanh lịch.', 'https://cdn.vuahanghieu.com/unsafe/0x900/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2023/04/nuoc-hoa-nu-bvlgari-omnia-crystalline-edt-5ml-64390f2e7b4ef-14042023153038.jpg', 30),

('BVLGARI Rose Goldea Eau de Parfum Mini', 4, 1, 1, 2000000, N'BVLGARI Rose Goldea Eau de Parfum Mini là một hương thơm nữ tính và quyến rũ, lấy cảm hứng từ vẻ đẹp của hoa hồng. Hương đầu mở ra với sự tươi mát của cam bergamot và quả lựu, mang lại cảm giác sảng khoái và ngọt ngào. Tiếp đến là hương giữa với sự hòa quyện của hoa hồng Damask và hoa nhài, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn ấm áp của xạ hương và gỗ đàn hương, mang lại cảm giác sang trọng và tinh tế. Rose Goldea là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa nhẹ nhàng, vừa quyến rũ, lý tưởng cho những buổi tối lãng mạn.', 'https://product.hstatic.net/1000340570/product/bvlgari-rose-goldea-delight-5ml_e013a0a91522449abcf4d5b4eae43cff_master.jpg', 30),

('BVLGARI Le Gemme Gyan Eau de Parfum', 5, 1, 1, 2900000, N'BVLGARI Le Gemme Gyan Eau de Parfum là một hương thơm nam tính và bí ẩn, lấy cảm hứng từ đá sapphire xanh. Hương đầu mở ra với sự tươi mát của cam bergamot và bạch đậu khấu, mang lại cảm giác sảng khoái và tươi mới. Tiếp đến là hương giữa với sự hòa quyện của hoa nhài và cây hoắc hương, tạo nên một tầng hương đầy nam tính và lôi cuốn. Cuối cùng, hương cuối để lại dấu ấn ấm áp của gỗ đàn hương và nhựa hương, mang lại cảm giác sâu lắng và quyến rũ. Gyan là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa mạnh mẽ, vừa tinh tế, lý tưởng cho những người đàn ông mạnh mẽ và tự tin.', 'https://apaniche.vn/wp-content/uploads/2023/10/bvlgari-le-gemme-gyan-edp-apa-niche.jpg', 25),

('BVLGARI Le Gemme Ambero Eau de Parfum', 5, 1, 1, 7000000, N'BVLGARI Le Gemme Ambero Eau de Parfum là một hương thơm unisex đầy sang trọng và quyến rũ, lấy cảm hứng từ đá hổ phách. Hương đầu mở ra với sự tươi mát của cam bergamot và gừng, mang lại cảm giác sảng khoái và tràn đầy năng lượng. Tiếp đến là hương giữa với sự hòa quyện của hoa nhài và cây hoắc hương, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn ấm áp của hổ phách và gỗ tuyết tùng, mang lại cảm giác thanh lịch và tinh tế. Ambero là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa mạnh mẽ, vừa tinh tế, lý tưởng cho những dịp đặc biệt.', 'https://kenperfume.com/wp-content/uploads/2023/05/LE-GEMME-AMBERO-EAU-DE-PARFUM-b.jpg', 25),

('BVLGARI Le Gemme Selima Eau de Parfum', 5, 1, 1, 4800000, N'BVLGARI Le Gemme Selima Eau de Parfum là một hương thơm nữ tính và quyến rũ, lấy cảm hứng từ đá carnelian đỏ. Hương đầu mở ra với sự tươi mát của cam bergamot và quế, mang lại cảm giác sảng khoái và ngọt ngào. Tiếp đến là hương giữa với sự hòa quyện của hoa hồng và hoa nhài, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn ấm áp của vani và nhựa hương, mang lại cảm giác sang trọng và tinh tế. Selima là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa nhẹ nhàng, vừa quyến rũ, lý tưởng cho những buổi tối lãng mạn và sang trọng.', 'https://microless.com/cdn/products/fa063a3f4647583434d03f79e2078508-hi.jpg', 25),


('Yves Saint Laurent Mon Paris Couture', 2, 2, 2, 3200000, N'Mon Paris Couture là phiên bản nâng cấp của Mon Paris, với hương thơm tươi mới và sôi động hơn. Hương đầu là sự kết hợp của cam bergamot và quả mâm xôi, tiếp đến là hương giữa của hoa nhài và hoa cam. Hương cuối là sự ấm áp của hoắc hương và xạ hương trắng, mang lại cảm giác sang trọng và tinh tế.', 'https://product.hstatic.net/1000340570/product/mon-paris-couture-yves-saint-laurent_398f9b8b33e04e94a9a0a3647c788d3b_master.jpg', 30),

('Yves Saint Laurent Y Eau de Parfum', 1, 2, 2, 3800000, N'Y Eau de Parfum là sự kết hợp hoàn hảo giữa hương gỗ và hương thảo mộc, mang đến cảm giác mạnh mẽ và nam tính. Hương đầu mở ra với sự tươi mát và ngọt ngào của quả táo xanh, gừng và cam bergamot, mang lại cảm giác sảng khoái và đầy năng lượng. Tiếp đến là hương giữa với sự hòa quyện của cây xô thơm, quả bách xù và hoa phong lữ đỏ, tạo nên một tầng hương đầy nam tính và lôi cuốn. Cuối cùng, hương cuối để lại dấu ấn ấm áp và nồng nàn của nhựa hương, đậu tonka, gỗ tuyết tùng, cỏ hương bài và nhựa hương olibanum.', 'https://product.hstatic.net/1000340570/product/yves-saint-laurent-y-eau-de-parfum-1_42ad04f05afa4c8a9fe801822f2b87e5_master.jpg', 30),

('Yves Saint Laurent La Nuit de L-Homme', 1, 2, 2, 3200000, N'La Nuit de L-Homme là sự kết hợp giữa hương gỗ và hương gia vị, mang đến cảm giác bí ẩn và quyến rũ. Hương đầu mở ra với sự tươi mát của bạch đậu khấu, mang lại cảm giác sảng khoái và đầy năng lượng. Tiếp đến là hương giữa với sự hòa quyện của cam bergamot, gỗ tuyết tùng Virginia và hoa oải hương, tạo nên một tầng hương đầy nam tính và lôi cuốn. Cuối cùng, hương cuối để lại dấu ấn ấm áp và nồng nàn của cỏ hương bài và thì là Ba Tư, mang lại cảm giác bí ẩn và gợi cảm. La Nuit de L-Homme là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa mạnh mẽ, vừa tinh tế, lý tưởng cho những buổi tối lãng mạn hoặc các sự kiện đặc biệt. Thiết kế chai nước hoa với tông màu đen tuyền và hình dáng mạnh mẽ cũng góp phần tôn lên vẻ nam tính và cuốn hút của sản phẩm.', 'https://product.hstatic.net/1000340570/product/yves-saint-laurent-la-nuit-de-l_homme_facef14be622447cb8628095f5f82906_master.jpg', 30),

('Yves Saint Laurent Mon Paris Parfum Floral', 2, 2, 2, 3200000, N'Tiếp nối với sự thành công của Mon Paris, thương hiệu Yves Saint Laurent đã cho ra phiên bản tiếp nối với tên gọi Mon Paris Parfum Floral. Đây là một mùi hương nhẹ nhàng, lãng mạn nhưng không kém phần tinh tế và sang trọng, mang đến cảm giác như đang dạo bước trong một khu vườn đầy hoa dưới ánh nắng ban mai. Hương đầu mở ra với sự tươi mát và ngọt ngào của quả đào và cam chanh, mang lại cảm giác tươi mới và tràn đầy năng lượng. Tiếp đến là hương giữa với sự hòa quyện của các loài hoa như hoa mẫu đơn, hoa hồng trắng, cà độc dược, hoa mộc lan, hoa cam và hoa nhài, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn ấm áp và nồng nàn của xạ hương trắng, gỗ cashmere và hoắc hương, mang lại cảm giác thanh lịch và tinh tế. Thiết kế chai nước hoa Mon Paris Parfum Floral cũng rất tinh tế với những đường nét nữ tính và chiếc nơ đen thắt điệu đà ở phần cổ chai, tôn lên sự thanh lịch và cuốn hút. Đây chắc chắn là lựa chọn hoàn hảo cho những cô gái yêu thích phong cách sang trọng và tinh tế.', 'https://product.hstatic.net/1000340570/product/yves-saint-laurent-mon-paris-parfum-floral-100ml_57f7d84f343a42d4b7c1c09bbed3b5f0_master.jpg', 30),

('Yves Saint Laurent Mon Paris Intensement Eau de Parfum', 2, 2, 2, 3290000, N'Mon Paris Intensement là phiên bản đậm đà hơn của Mon Paris, với hương thơm nồng nàn và quyến rũ, mang đến cảm giác như một câu chuyện tình yêu say đắm ở Paris. Hương đầu mở ra với sự tươi mát và ngọt ngào của quả mâm xôi, quả lý chua đen, quả lê, quả cam và cam bergamot. Tiếp đến là hương giữa với sự hòa quyện của hoa hồng Bungari, hoa hồng tháng Năm, hoa mẫu đơn, hoa cà độc dược và hoa lan Nam Phi, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn ấm áp và nồng nàn của vanilla, xạ hương trắng, cây hoắc hương, cây cashmeran và benzoin. Mon Paris Intensement mang đến một mùi hương rực rỡ, thể hiện cảm xúc mãnh liệt trong tình yêu, vượt qua những thử thách và nắm bắt cơ hội một cách dữ dội. Thiết kế chai nước hoa cũng rất sang trọng với chiếc nơ nhung điệu đà ở phần cổ chai, tôn lên vẻ thanh lịch và cuốn hút của một quý cô Paris.', 'https://product.hstatic.net/1000340570/product/mon-paris-intensement-yves-saint-laurent_6a99f9da0abb4379bf80393c95ff5c54_master.jpg', 30),

('Yves Saint Laurent Tuxedo Eau de Parfum', 3, 2, 2, 7230000, N'Tuxedo là một mùi hương unisex đầy sang trọng và quyến rũ, lấy cảm hứng từ chiếc áo tuxedo biểu tượng của Yves Saint Laurent. Hương đầu mở ra với sự tươi mát của cam bergamot và bạch đậu khấu, mang lại cảm giác sảng khoái và tươi mới. Tiếp đến là hương giữa với sự hòa quyện của hoa hồng và hạt tiêu đen, tạo nên một tầng hương đầy bí ẩn và lôi cuốn. Cuối cùng, hương cuối để lại dấu ấn ấm áp của hoắc hương và vani, mang lại cảm giác sang trọng và tinh tế. Tuxedo là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa mạnh mẽ, vừa tinh tế, lý tưởng cho những dịp đặc biệt hoặc sử dụng hàng ngày', 'https://product.hstatic.net/200000201387/product/18_7e4d5cf7abc845b394110cf1aff24d09_master.jpg', 30),

('Yves Saint Laurent Cuir Eau de Parfum', 3, 2, 2, 6615000, N'Cuir là một mùi hương unisex mạnh mẽ và đầy cá tính, với sự kết hợp của các hương liệu da thuộc và gỗ. Hương đầu mở ra với sự tươi mát của cam bergamot và bạch đậu khấu, mang lại cảm giác sảng khoái và tươi mới. Tiếp đến là hương giữa với sự hòa quyện của hoa nhài và hoa hồng, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn ấm áp của da thuộc, hoắc hương và gỗ tuyết tùng, mang lại cảm giác bí ẩn và cuốn hút. Cuir là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa mạnh mẽ, vừa tinh tế, lý tưởng cho những dịp đặc biệt hoặc sử dụng hàng ngày', 'https://kallos.co/cdn/shop/files/dau-thom-ysl-cuir-le-vestiaire-des-parfums_8.jpg?v=1712570875&width=900', 30),

('Yves Saint Laurent Saharienne Eau de Parfum', 3, 2, 2, 4710000, N'Saharienne là một mùi hương unisex tươi mát và sảng khoái, lấy cảm hứng từ những chuyến phiêu lưu trong sa mạc. Hương đầu mở ra với sự tươi mát của cam bergamot và chanh vàng, mang lại cảm giác sảng khoái và tràn đầy năng lượng. Tiếp đến là hương giữa với sự hòa quyện của hoa nhài và hoa cam, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn ấm áp của xạ hương trắng và gỗ tuyết tùng, mang lại cảm giác thanh lịch và tinh tế. Saharienne là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa mạnh mẽ, vừa tinh tế, lý tưởng cho những dịp đặc biệt hoặc sử dụng hàng ngày', 'https://theperfume.vn/wp-content/uploads/2018/11/ysl-saharienne-le-vestiaire-des-parfums-125ml.png', 30),

('Yves Saint Laurent Libre Eau de Parfum Mini', 4, 2, 2, 450000, N'Yves Saint Laurent Libre Eau de Parfum Mini là một hương thơm nữ tính, mạnh mẽ và đầy tự do. Hương đầu mở ra với sự tươi mát của cam quýt và quả lý chua đen. Hương giữa là sự hòa quyện của hoa nhài và hoa oải hương. Hương cuối là sự ấm áp của vanilla, gỗ tuyết tùng và xạ hương, tạo nên một mùi hương quyến rũ và sang trọng.', 'https://myphamvina.net/uploads/product/2390/YSLLIBREMINI1.jpg', 30),

('Yves Saint Laurent Y Eau de Parfum Mini', 4, 2, 2, 380000, N'Yves Saint Laurent Y Eau de Parfum Mini là một hương thơm nam tính, mạnh mẽ và cuốn hút. Hương đầu tươi mát với cam bergamot và gừng. Hương giữa hòa quyện của cây xô thơm và quả bách xù. Hương cuối ấm áp với gỗ tuyết tùng và hổ phách, mang lại cảm giác sâu lắng và quyến rũ. Yves Saint Laurent Y EDP Intense là sự lựa chọn hoàn hảo cho những người đàn ông muốn thể hiện sự tự tin, quyết đoán và cá tính. Với hương thơm đậm đà, cuốn hút và đầy phóng khoáng, Y EDP Intense giúp bạn nổi bật với sự mạnh mẽ nhưng vẫn tinh tế và thanh lịch.', 'https://orchard.vn/wp-content/uploads/2024/09/yves-saint-laurent-y-edp-intense-mini-7-5ml_2.jpg.webp', 30),

('Chanel Égoïste Platinum Eau de Toilette', 1, 3, 3, 2980000, N'Égoïste Platinum Eau de Toilette là một hương thơm nam tính, sang trọng và đầy quyến rũ. Hương đầu mở ra với sự tươi mát của cam bergamot, chanh và hoa oải hương. Hương giữa là sự hòa quyện của cây xô thơm, húng quế và hoa phong lữ. Hương cuối là sự ấm áp của gỗ tuyết tùng, cỏ hương bài và hổ phách. Đây là một mùi hương lý tưởng cho những người đàn ông lịch lãm và tinh tế.', 'https://cdn.vuahanghieu.com/unsafe/0x900/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2022/02/nuoc-hoa-nam-chanel-egoiste-platinum-edt-100ml-6209cf3a31227-14022022104042.jpg', 30),

('Chanel No. 5 Eau de Parfum', 2, 3, 3, 3850000, N' Chanel No. 5 Eau de Parfum là một hương thơm kinh điển và biểu tượng của sự sang trọng. Hương đầu mở ra với sự tươi mát của aldehyde, hoa ylang-ylang và cam bergamot. Hương giữa là sự hòa quyện của hoa nhài, hoa hồng và hoa lily. Hương cuối là sự ấm áp của gỗ đàn hương, vani và cỏ hương bài. Đây là một mùi hương lý tưởng cho những người phụ nữ yêu thích sự thanh lịch và quyến rũ.', 'https://product.hstatic.net/1000340570/product/chanel-no-5-eau-de-parfum-100ml_63551a95c77340fda723b052669b3cac_master.jpg', 30),

('Chanel Coco Mademoiselle Eau de Parfum', 2, 3, 3, 4550000, N'Coco Mademoiselle Eau de Parfum là một hương thơm nữ tính, tươi mát và đầy quyến rũ. Hương đầu mở ra với sự tươi mát của cam, quýt và cam bergamot. Hương giữa là sự hòa quyện của hoa nhài, hoa hồng và quả lý chua đen. Hương cuối là sự ấm áp của hoắc hương, vani và xạ hương trắng. Đây là một mùi hương lý tưởng cho những người phụ nữ hiện đại và tự tin.', 'https://product.hstatic.net/1000340570/product/chanel-coco-mademoiselle-eau-de-parfum-100ml_d2c6a6c0c51e4ec5ba1243bee4b1191c_master.jpg', 30),

('Chanel Les Exclusifs de Chanel Sycomore Eau de Parfum', 3, 3, 3, 11700000, N'Les Exclusifs de Chanel Sycomore Eau de Parfum là một hương thơm unisex đầy sang trọng và tinh tế. Hương đầu mở ra với sự tươi mát của cam bergamot và bạch đậu khấu. Hương giữa là sự hòa quyện của hoa nhài và cỏ hương bài. Hương cuối là sự ấm áp của gỗ tuyết tùng, hoắc hương và nhựa hương. Đây là một mùi hương lý tưởng cho những người yêu thích sự thanh lịch và tinh tế.', 'https://www.chanel.com/images//t_one//w_0.51,h_0.51,c_crop/q_auto:good,f_autoplus,fl_lossy,dpr_1.1/w_840/sycomore-les-exclusifs-de-chanel-eau-de-parfum-6-8fl-oz--packshot-default-122300-9536679313438.jpg', 30),

('Chanel Les Exclusifs de Chanel 1957 Eau de Parfum', 3, 3, 3, 11700000, N'Les Exclusifs de Chanel 1957 Eau de Parfum là một hương thơm unisex đầy quyến rũ và bí ẩn. Hương đầu mở ra với sự tươi mát của cam bergamot và hạt tiêu hồng. Hương giữa là sự hòa quyện của hoa nhài, hoa cam và hoa hồng. Hương cuối là sự ấm áp của xạ hương trắng, vani và hoắc hương. Đây là một mùi hương lý tưởng cho những người yêu thích sự sang trọng và bí ẩn.', 'https://lanperfume.com/wp-content/uploads/2024/07/les-exclusifs-de-chanel-1957-1-1.jpg', 30),

('Chanel Les Exclusifs de Chanel Coromandel Eau de Parfum', 3, 3, 3, 11700000, N'Les Exclusifs de Chanel Coromandel Eau de Parfum là một hương thơm unisex đầy mạnh mẽ và cuốn hút. Hương đầu mở ra với sự tươi mát của cam bergamot và hạt tiêu đen. Hương giữa là sự hòa quyện của hoa nhài và hoa hồng. Hương cuối là sự ấm áp của hoắc hương, nhựa hương và vani. Đây là một mùi hương lý tưởng cho những người yêu thích sự mạnh mẽ và cuốn hút.', 'https://kenperfume.com/wp-content/uploads/2023/07/Les-Exclusifs-De-Chanel-Coromandel.jpg', 30),

('Dior Homme Intense', 1, 4, 4, 3600000, N'Hương thơm gỗ và hoa cỏ với hương đầu của oải hương, hương giữa của hoa diên vĩ và hương cuối của gỗ tuyết tùng và cỏ hương bài. Mùi hương này mang lại cảm giác sang trọng và lịch lãm. Dior Homme Intense là sự kết hợp hoàn hảo giữa sự mạnh mẽ và tinh tế, lý tưởng cho những dịp đặc biệt. Hương thơm này còn có sự ấm áp và quyến rũ từ hổ phách và gỗ quý.', 'https://product.hstatic.net/1000340570/product/dior-homme-intense-1_3b6dc09e545441e4bd989b178c98f55e_master.jpg', 25),

('Christian Dior Fahrenheit Eau de Toilette', 1, 4, 4, 2650000, N'Một hương thơm cổ điển với hương đầu của cam bergamot và chanh, hương giữa của hoa violet và hương cuối của da thuộc và gỗ đàn hương. Đây là một mùi hương mạnh mẽ và nam tính. Fahrenheit mang lại cảm giác ấm áp và đầy sức sống, phù hợp cho những người đàn ông yêu thích sự tự do và phiêu lưu. Hương thơm này còn có sự kết hợp độc đáo giữa các nốt hương gỗ và da thuộc.', 'https://product.hstatic.net/1000340570/product/fahrenheit-christian-dior-for-men_41c944dba34842ba98d3d31dd20082cd_master.jpg', 25),

('Dior Miss Dior Eau De Parfum', 2, 4, 4, 3150000, N'Hương thơm tươi mát và ngọt ngào với hương đầu của cam bergamot, hương giữa của hoa hồng và hoa nhài, và hương cuối của hoắc hương và xạ hương. Mùi hương này mang lại cảm giác trẻ trung và lôi cuốn. Miss Dior là biểu tượng của sự lãng mạn và tinh tế, hoàn hảo cho những buổi hẹn hò. Hương thơm này còn có sự kết hợp của các nốt hương hoa và gỗ, tạo nên một mùi hương đầy sức sống.', 'https://product.hstatic.net/1000340570/product/dior-miss-dior-eau-de-parfum_d571e408b8f642e080859fafab4c9e49_master.jpg', 40),

('Dior J-adore Eau de Parfum', 2, 4, 4, 3450000, N'Một hương thơm hoa cỏ với hương đầu của cam bergamot, hương giữa của hoa nhài và hoa hồng, và hương cuối của xạ hương và vani. J-adore mang lại cảm giác sang trọng và tinh tế, như một bó hoa tươi thắm. Hương thơm này là sự kết hợp hoàn hảo của các loài hoa quý từ khắp nơi trên thế giới, tạo nên một mùi hương nữ tính và quyến rũ, lý tưởng cho những dịp đặc biệt.', 'https://product.hstatic.net/1000340570/product/dior-j_adore-eau-de-parfum-100ml_f1bb24e8b658431e93fe3f2ca4ed7f99_master.jpg', 40),
    ('Gris Dior', 3, 4, 4, 5700000, N'Một hương thơm chypre và citrus với hương đầu của cam bergamot, hương giữa của hoa hồng và hoa nhài, và hương cuối của hoắc hương và xạ hương. Gris Dior mang lại cảm giác sang trọng và bí ẩn, như một bức tranh màu xám đầy nghệ thuật. Hương thơm này là sự kết hợp hoàn hảo của các nốt hương hoa và gỗ, tạo nên một mùi hương đầy sức sống và thanh lịch.', 'https://clmensstore.com/wp-content/uploads/2022/05/gris_dior_1850x2000_3db15d7d-c698-45b7-ab9f-e55687e1fc8d_1850x-948x1024.jpg', 30),

(' Dior Eden-Roc', 3, 4, 4, 5600000, N'Hương thơm tươi mát và biển cả với hương đầu của cam bergamot và chanh, hương giữa của hoa nhài và hoa cam, và hương cuối của gỗ đàn hương và xạ hương. Eden-Roc là sự kết hợp hoàn hảo giữa thiên nhiên và sự sang trọng, lý tưởng cho mùa hè. Hương thơm này còn có sự kết hợp của các nốt hương biển và hoa, tạo nên một mùi hương tươi mát và đầy sức sống.', 'https://cdn.tophuong.com/nuoc-hoa/p/christian-dior-eden-roc-unisex.jpg', 30),

('Dior Jasmin des Anges', 3, 4, 4, 6000000, N'Một hương thơm hoa cỏ và trái cây với hương đầu của cam bergamot và quả lê, hương giữa của hoa nhài và hoa cam, và hương cuối của xạ hương và vani. Jasmin des Anges mang lại cảm giác ấm áp và ngọt ngào, như một buổi chiều mùa hè đầy nắng. Hương thơm này còn có sự kết hợp của các nốt hương mật ong và quả mơ, tạo nên một mùi hương đầy sức sống và quyến rũ.', 'https://clmensstore.com/wp-content/uploads/2022/08/Jasmin-Des-Anges-Dior-768x767.jpg', 30),

('Dior Ambre Nuit', 5, 4, 4, 6000000, N'Một hương thơm ấm áp và gợi cảm với hương đầu của cam bergamot và bưởi, hương giữa của hoa hồng và hổ phách, và hương cuối của gỗ đàn hương và xạ hương. Ambre Nuit mang lại cảm giác bí ẩn và lôi cuốn, như một buổi dạ tiệc dưới ánh đèn vàng. Hương thơm này là sự kết hợp hoàn hảo của các nốt hương hoa và gỗ, tạo nên một mùi hương đầy sức sống và sang trọng.', 'https://clmensstore.com/wp-content/uploads/2022/07/Ambre-Nuit-768x767.jpg', 30),

('Dior Oud Ispahan', 5, 4, 4, 5700000, N'Hương thơm mạnh mẽ và bí ẩn với hương đầu của hoa hồng và nhựa cây, hương giữa của gỗ đàn hương và hổ phách, và hương cuối của xạ hương và gỗ tuyết tùng. Oud Ispahan là sự kết hợp hoàn hảo giữa truyền thống và hiện đại, lý tưởng cho những người yêu thích sự độc đáo. Hương thơm này còn có sự kết hợp của các nốt hương gỗ và nhựa cây, tạo nên một mùi hương đầy sức sống và sang trọng.', 'https://clmensstore.com/wp-content/uploads/2022/06/Dior-Oud-Ispahan-768x767.jpg', 30),

('Dior J-adore Eau de Parfum Mini Size', 2, 4, 4, 3450000, N'Một hương thơm hoa cỏ với hương đầu của cam bergamot, hương giữa của hoa nhài và hoa hồng, và hương cuối của xạ hương và vani. J-adore mang lại cảm giác sang trọng và tinh tế, như một bó hoa tươi thắm. Hương thơm này là sự kết hợp hoàn hảo của các loài hoa quý từ khắp nơi trên thế giới, tạo nên một mùi hương nữ tính và quyến rũ, lý tưởng cho những dịp đặc biệt.', 'https://orchard.vn/wp-content/uploads/2024/09/dior-jadore-infinissime-edp-mini-5ml_3.jpg.webp', 20),

('Dior Jasmin des Anges Mini Size', 4, 4, 4, 625000, N'Một hương thơm hoa cỏ và trái cây với hương đầu của cam bergamot và quả lê, hương giữa của hoa nhài và hoa cam, và hương cuối của xạ hương và vani. Jasmin des Anges mang lại cảm giác ấm áp và ngọt ngào, như một buổi chiều mùa hè đầy nắng. Hương thơm này còn có sự kết hợp của các nốt hương mật ong và quả mơ, tạo nên một mùi hương đầy sức sống và quyến rũ.', 'https://clmensstore.com/wp-content/uploads/2022/08/3348901629874_3-768x768.webp', 50),

('Dior Ambre Nuit Mini Size', 4, 4, 4, 625000, N'Một hương thơm ấm áp và gợi cảm với hương đầu của cam bergamot và bưởi, hương giữa của hoa hồng và hổ phách, và hương cuối của gỗ đàn hương và xạ hương. Ambre Nuit mang lại cảm giác bí ẩn và lôi cuốn, như một buổi dạ tiệc dưới ánh đèn vàng. Hương thơm này là sự kết hợp hoàn hảo của các nốt hương hoa và gỗ, tạo nên một mùi hương đầy sức sống và sang trọng.', 'https://clmensstore.com/wp-content/uploads/2022/07/Y0958160_E02_ZHC-768x512.jpg', 50),

('Dior Oud Ispahan Mini Size', 5, 4, 4, 600000, N'Hương thơm mạnh mẽ và bí ẩn với hương đầu của hoa hồng và nhựa cây, hương giữa của gỗ đàn hương và hổ phách, và hương cuối của xạ hương và gỗ tuyết tùng. Oud Ispahan là sự kết hợp hoàn hảo giữa truyền thống và hiện đại, lý tưởng cho những người yêu thích sự độc đáo. Hương thơm này còn có sự kết hợp của các nốt hương gỗ và nhựa cây, tạo nên một mùi hương đầy sức sống và sang trọng.', 'https://clmensstore.com/wp-content/uploads/2022/06/Y0909280_E02_ZHC-768x512.jpg', 50),

('Kilian Dark Lord, Ex Tenebris Lux', 1, 5, 5, 7800000, N'Kilian Dark Lord - "Ex Tenebris Lux" là một hương nước hoa mạnh mẽ và nam tính, với hương da thuộc, rượu rum và gỗ. Hương thơm này mang đến cảm giác bí ẩn và quyền lực, phù hợp cho những dịp đặc biệt hoặc khi bạn muốn để lại ấn tượng mạnh mẽ. Tầng hương cuối cùng của hoắc hương và xạ hương tạo nên một sự kết hợp hoàn hảo, mang đến sự bền lâu và quyến rũ.', 'https://product.hstatic.net/1000340570/product/kilian-dark-lord_-ex-tenebris-lux_bc762945b4ff4b8a9857e30307110770_master.jpg', 20),

('Kilian Straight to Heaven, white cristal', 1, 5, 5, 7100000, N'Đây là một hương nước hoa mạnh mẽ và đầy nam tính, mở đầu với hương rượu rum nồng nàn, kết hợp với hương vani ngọt ngào và trái cây khô. Hương gỗ tuyết tùng và hoắc hương tạo nên một nền tảng ấm áp và bền lâu, mang đến cảm giác quyến rũ và bí ẩn. Hương thơm này thích hợp cho những buổi tối lãng mạn hoặc các sự kiện đặc biệt, khi bạn muốn để lại ấn tượng mạnh mẽ và khó quên.', 'https://product.hstatic.net/1000340570/product/straight-to-heaven-by-kilian-for-men_379b217c261e4749a14a1f92a8c77e9c_master.jpg', 25),

('Kilian Good Girl Gone Bad', 2, 5, 5, 6850000, N'Hương nước hoa này mang đến cảm giác nữ tính và quyến rũ, mở đầu với hương hoa nhài, hoa huệ và hoa hồng. Tầng hương giữa là sự kết hợp của hoa cam và hoa mộc lan, tạo nên một sự ngọt ngào và tươi mới. Cuối cùng, hương gỗ tuyết tùng và hổ phách mang đến sự ấm áp và bền lâu. Đây là lựa chọn lý tưởng cho những buổi hẹn hò hoặc các sự kiện quan trọng, khi bạn muốn tỏa sáng với sự nữ tính và quyến rũ.', 'https://product.hstatic.net/1000340570/product/kilian_good_girl_gone_bad_edp_8cd5a04016154ae6ae11c17c89b4f33a_master.jpg', 12),

('Kilian Love, Dont Be Shy', 2, 5, 5, 6300000, N'Kilian Love, Dont Be Shy là một hương nước hoa ngọt ngào và lãng mạn, mở đầu với hương cam tươi mát, kết hợp với vani và kẹo marshmallow. Tầng hương giữa là sự hòa quyện của hoa cam và hoa nhài, mang đến sự nữ tính và quyến rũ. Cuối cùng, hương xạ hương và hổ phách tạo nên một nền tảng ấm áp và bền lâu. Hương thơm này thích hợp cho những buổi tối lãng mạn hoặc khi bạn muốn cảm thấy ngọt ngào và đáng yêu.', 'https://xxivstore.com/wp-content/uploads/2020/07/love-eau-de-parfum-50ml-72e-768x768.png', 28),

('Kilian Rolling in Love', 2, 5, 5, 5950000, N'Hương nước hoa này mang đến cảm giác ấm áp và gợi cảm, mở đầu với hương hạnh nhân và hoa diên vĩ. Tầng hương giữa là sự kết hợp của hoa cam và hoa nhài, tạo nên sự ngọt ngào và nữ tính. Cuối cùng, hương xạ hương và hổ phách mang đến sự ấm áp và bền lâu. Đây là lựa chọn hoàn hảo cho những ai muốn tỏa sáng với sự tự tin và quyến rũ.', 'https://product.hstatic.net/1000340570/product/kilian-rolling-in-love-1_ad737f42cbaf404d8717f27e76f4db60_master.jpg', 20),

('Kilian Angels Share', 3, 5, 5, 5350000, N'Kilian Angels Share là một hương nước hoa ấm áp và sang trọng, mở đầu với hương rượu cognac, quế và đậu tonka. Tầng hương giữa là sự kết hợp của gỗ tuyết tùng và hổ phách, tạo nên sự ấm áp và bền lâu. Cuối cùng, hương vani và xạ hương mang đến sự ngọt ngào và quyến rũ. Hương thơm này thích hợp cho cả nam và nữ, đặc biệt là trong những dịp đặc biệt hoặc khi bạn muốn cảm thấy sang trọng và quý phái.', 'https://product.hstatic.net/1000340570/product/kilian-angels_-share_385c0a1038714d1184bef41ba1e76c94_master.jpg', 20),

('Kilian Apple Brandy on the Rocks', 3, 5, 5, 5350000, N'Hương nước hoa này mang đến cảm giác tươi mát và sảng khoái, mở đầu với hương táo và rượu brandy. Tầng hương giữa là sự kết hợp của gỗ tuyết tùng và hổ phách, tạo nên sự ấm áp và bền lâu. Cuối cùng, hương xạ hương và vani mang đến sự ngọt ngào và quyến rũ. Đây là lựa chọn hoàn hảo cho những ngày hè nóng bức hoặc khi bạn muốn cảm thấy tươi mới và sảng khoái.', 'https://product.hstatic.net/1000340570/product/kilian-apple-brandy-on-the-rocks.jpg1_898f375a7b6f4c0fb6ee9a7ce74ad335_master.jpg', 15),

('Kilian Sacred Wood', 3, 5, 5, 5000000, N'Kilian Sacred Wood là một hương nước hoa thanh lịch và tinh tế, mở đầu với hương gỗ đàn hương và gỗ tuyết tùng. Tầng hương giữa là sự kết hợp của hổ phách và xạ hương, tạo nên sự ấm áp và bền lâu. Cuối cùng, hương vani và đậu tonka mang đến sự ngọt ngào và quyến rũ. Hương thơm này thích hợp cho cả nam và nữ, đặc biệt là trong những dịp quan trọng hoặc khi bạn muốn cảm thấy thanh lịch và tinh tế.', 'https://apaniche.vn/wp-content/uploads/2024/05/Killian-Sacred-Wood-EDP-gia-tot-nhat.jpg', 16),

('Kilian Miniature Set 5X10ml', 4, 5, 5, 6280000, N'Bộ sưu tập này gồm 5 chai mini 10ml của các mùi hương nổi tiếng như Good Girl Gone Bad, Love, Dont Be Shy, Black Phantom, Straight to Heaven và Angels Share. Đây là lựa chọn hoàn hảo cho những ai muốn thử nhiều mùi hương khác nhau mà không cần mua chai lớn. Các chai mini này cũng rất tiện lợi để mang theo khi du lịch hoặc làm quà tặng.', 'https://bizweb.dktcdn.net/100/106/604/products/giftset-kilian-5pcs-orchard-vn-2.jpg?v=1662258743803', 10),

('Kilian Back to Black, aphrodisiac', 5, 5, 5, 6900000, N'Kilian Back to Black, aphrodisiac là một hương nước hoa độc đáo và gợi cảm, mở đầu với hương mật ong, thuốc lá và vani. Tầng hương giữa là sự kết hợp của hoa cam và hoa nhài, tạo nên sự ngọt ngào và nữ tính. Cuối cùng, hương xạ hương và hổ phách mang đến sự ấm áp và bền lâu. Hương thơm này thích hợp cho những dịp đặc biệt hoặc khi bạn muốn cảm thấy quyến rũ và bí ẩn.', 'https://bizweb.dktcdn.net/thumb/1024x1024/100/465/306/products/8-1670072529473.png?v=1670072532560', 18),

('Kilian Moonlight in Heaven', 5, 5, 5, 6950000, N'Hương nước hoa này mang đến cảm giác tươi mát và lạ lẫm, mở đầu với hương xoài, dừa và gạo. Tầng hương giữa là sự kết hợp của hoa cam và hoa nhài, tạo nên sự ngọt ngào và nữ tính. Cuối cùng, hương xạ hương và hổ phách mang đến sự ấm áp và bền lâu. Đây là lựa chọn hoàn hảo cho những ngày hè hoặc khi bạn muốn cảm thấy tươi mới và sảng khoái.', 'https://product.hstatic.net/1000340570/product/kilian-moonlight-in-heaven_11404fdc18bf473d812c72b60c9cf154_master.jpg', 30),

('Kilian Vodka on the Rocks', 5, 5, 5, 4500000, N'Kilian Vodka on the Rocks là một hương nước hoa tươi mát và sảng khoái, mở đầu với hương rượu vodka, bạch đậu khấu và rêu. Tầng hương giữa là sự kết hợp của gỗ tuyết tùng và hổ phách, tạo nên sự ấm áp và bền lâu. Cuối cùng, hương xạ hương và vani mang đến sự ngọt ngào và quyến rũ. Hương thơm này thích hợp cho cả nam và nữ, đặc biệt là trong những dịp quan trọng hoặc khi bạn muốn cảm thấy tươi mới và sảng khoái.', 'https://product.hstatic.net/200000561331/product/ki_eff37319fb1b4cc5a0f763d0e95d3b27_master.jpg', 25),

('Jean Paul Gaultier Le Male', 1, 7, 7, 2550000, N'Hiện đại, an yên và nhẹ nhàng là những gì ta có thể nhanh chóng thấy được trong Jean Paul Gaultier Le Male, kể cả là từ tông hương đầu tiên. Dưới sự cộng hưởng đầy ăn nhập, Bạch đậu khấu và Bạc hà nhuốm lấy khứu giác hương thơm thanh cay, mềm mại, hòa quyện với Oải hương miên man cùng Cam bergamot. Không sôi nổi năng động, Le Male thể hiện bản chất lịch lãm, an toàn của mình bằng cách kết hợp mộc mạc giữa Hoa cam và Quế, nồng nàn và ấm áp khôn xiết. Như một cái ôm siết ngày lạnh, Đàn hương, Vanilla cùng Tuyết tùng càng in đậm trong ta hình ảnh của một người tĩnh tại, thư thái cùng những khí chất không phải quý ông nào cũng may mắn có được.', 'https://product.hstatic.net/1000340570/product/jean-paul-gaultier-le-male_9afb9f3204674486b002004ac92aeb35_master.jpg', 20),

('Jean Paul Gaultier Ultra Male', 1, 7, 7, 2880000, N'Jean Paul Gaultier Ultra Male là một phiên bản mạnh mẽ hơn của Le Male, ra mắt vào năm 2015. Hương thơm mở đầu với sự tươi mát của cam bergamot và chanh, kết hợp với sự ngọt ngào của quả lê và bạc hà. Hương giữa là sự pha trộn của quế và cây xô thơm, tạo nên một lớp hương ấm áp và cay nồng. Cuối cùng, hương gỗ tuyết tùng và hổ phách mang lại sự ấm áp và nam tính. Ultra Male là một mùi hương đầy sức sống và quyến rũ, lý tưởng cho mùa thu và đông.', 'https://product.hstatic.net/1000340570/product/ultra-male_d01923d930dc49b7b5900eef6a211aca_master.jpg', 20),

('Jean Paul Gaultier Le Beau', 1, 7, 7, 2710000, N'Jean Paul Gaultier Le Beau là một hương thơm tươi mát và gợi cảm, ra mắt vào năm 2019. Hương thơm mở đầu với sự tươi mát của cam bergamot, mang lại cảm giác sảng khoái và đầy năng lượng. Tiếp đến là hương giữa của dừa và đậu tonka, tạo nên một lớp hương ngọt ngào và ấm áp. Cuối cùng, hương hổ phách và gỗ đàn hương kết hợp hoàn hảo, để lại một dấu ấn nam tính và quyến rũ. Le Beau là một mùi hương lý tưởng cho những ngày hè và những dịp đặc biệt.', 'https://product.hstatic.net/1000340570/product/jean-paul-gaultier-le-beau-for-men_2f874a37049c4375a38f31a0b96a87a4_master.jpg', 25),

('Jean Paul Gaultier Scandal', 2, 7, 7, 3470000, N'Jean Paul Gaultier Scandal là một hương thơm đầy năng lượng và lôi cuốn, ra mắt vào năm 2017. Hương thơm mở đầu với sự tươi mát của quýt và cây xô thơm, mang lại cảm giác sảng khoái và đầy năng lượng. Tiếp đến là hương giữa của caramel, tạo nên một lớp hương ngọt ngào và hấp dẫn. Cuối cùng, hương đậu tonka và cỏ hương bài mang lại sự ấm áp và nam tính. Scandal là một mùi hương đầy sức sống và quyến rũ, hoàn hảo cho những dịp đặc biệt.', 'https://product.hstatic.net/1000340570/product/jean-paul-gaultier-scandal_3047bba5929f420a93ea42029a0cc264_master.jpg', 30),

('Jean Paul Gaultier La Belle', 2, 7, 7, 3510000, N'Jean Paul Gaultier La Belle là một hương thơm gợi cảm và nữ tính, ra mắt vào năm 2019. Hương thơm mở đầu với sự tươi mát của quả lê và cam bergamot, mang lại cảm giác sảng khoái và đầy năng lượng. Tiếp đến là hương giữa của hoa nhài và ylang-ylang, tạo nên một lớp hương ngọt ngào và quyến rũ. Cuối cùng, hương vanilla và hổ phách kết hợp hoàn hảo, để lại một dấu ấn ấm áp và gợi cảm trên da. La Belle là một mùi hương lý tưởng cho cả ngày và đêm.', 'https://product.hstatic.net/1000340570/product/jean-paul-gaultier-la-belle-for-women_b4b449eb9f9d488f960ddccac4f6b145_master.jpg', 30),

('Jean Paul Gaultier Le Male Le Parfum', 1, 7, 7, 2600000, N'Jean Paul Gaultier Le Male Le Parfum là một hương thơm mạnh mẽ và quyến rũ, ra mắt vào năm 2020. Hương thơm mở đầu với sự tươi mát của bạch đậu khấu, mang lại cảm giác sảng khoái và đầy năng lượng. Tiếp đến là hương giữa của hoa diên vĩ và oải hương, tạo nên một lớp hương thanh lịch và quyến rũ. Cuối cùng, hương vanilla và hổ phách kết hợp hoàn hảo, để lại một dấu ấn ấm áp và ngọt ngào trên da. Le Male Le Parfum là một mùi hương đầy nam tính và cuốn hút, lý tưởng cho buổi tối và những dịp đặc biệt.', 'https://product.hstatic.net/1000340570/product/jean-paul-gaultier-le-male-le-parfum-2_278e4828e76849acab55e5dc611a71f1_master.jpg', 30),


('Jean Paul Gaultier So Scandal', 4, 7, 7, 3470000, N'Jean Paul Gaultier So Scandal là một hương thơm đầy táo bạo và quyến rũ, ra mắt vào năm 2020. Hương thơm mở đầu với sự tươi mát của hoa cam và quả mâm xôi, mang lại cảm giác sảng khoái và đầy năng lượng. Tiếp đến là hương giữa của hoa nhài và hoa huệ, tạo nên một lớp hương ngọt ngào và quyến rũ. Cuối cùng, hương vanilla và hổ phách kết hợp hoàn hảo, để lại một dấu ấn ấm áp và gợi cảm trên da. So Scandal là một mùi hương lý tưởng cho những dịp đặc biệt và buổi tối.', 'https://product.hstatic.net/1000340570/product/jean-paul-gaultier-so-scandal-3_b678cdfa71d64ea5857e68a7008171b6_master.jpg', 40),

('Jean Paul Gaultier Le Male Elixir', 4, 7, 7, 3860000, N'Jean Paul Gaultier Le Male Elixir là một hương thơm mạnh mẽ và nam tính, ra mắt vào năm 2023. Hương thơm mở đầu với sự tươi mát của cam bergamot và chanh, mang lại cảm giác sảng khoái và đầy năng lượng. Tiếp đến là hương giữa của quế và cây xô thơm, tạo nên một lớp hương ấm áp và cay nồng. Cuối cùng, hương gỗ tuyết tùng và hổ phách mang lại sự ấm áp và nam tính. Le Male Elixir là một mùi hương đầy sức sống và quyến rũ, lý tưởng cho mùa thu và đông.', 'https://product.hstatic.net/1000340570/product/jean-paul-gaultier-le-male-elixir-125ml_88f020a8658b411dbc9d06885258c017_master.jpg', 30),

('Jean Paul Gautier Scandal Mini Size', 4, 7, 7, 400000, N'Jean Paul Gaultier Scandal Eau de Parfum Mini là một hương thơm nữ tính, đầy quyến rũ và táo bạo, ra mắt vào năm 2017. Hương đầu mở ra với sự tươi mát của cam đỏ và quýt, mang lại cảm giác sảng khoái và ngọt ngào. Tiếp đến là hương giữa với sự hòa quyện của mật ong, hoa nhài, hoa cam và hoa sơn chi, tạo nên một tầng hương đầy nữ tính và quyến rũ. Cuối cùng, hương cuối để lại dấu ấn ấm áp của hoắc hương, cam thảo và sáp ong, mang lại cảm giác sâu lắng và gợi cảm. Scandal là sự kết hợp hoàn hảo giữa các thành phần hương liệu, tạo nên một mùi hương vừa mạnh mẽ, vừa tinh tế, lý tưởng cho những buổi tối lãng mạn hoặc các sự kiện đặc biệt. Thiết kế chai nước hoa mini với hình dáng độc đáo và nắp chai là đôi chân thon dài, cũng góp phần tôn lên vẻ quyến rũ và táo bạo của sản phẩm.', 'https://product.hstatic.net/1000340570/product/jean-paul-gautier-scandal-mini-size_1e81520e19434a759e5dda5b40b84bbd_master.jpg', 50),

('Jean Paul Gaultier Le Beau For Men Mini Size', 4, 7, 7, 390000, N'Le Beau For Men không chỉ là một mùi hương, mà còn là một tuyên ngôn về phong cách và sự tự tin. Hương thơm mở đầu với sự tươi mát, sảng khoái của cam Bergamot và dừa, như một làn gió biển mát lành. Tiếp đến, đậu Tonka mang lại sự ấm áp, ngọt ngào, tạo nên một lớp hương giữa đầy mê hoặc. Cuối cùng, hổ phách và gỗ đàn hương kết hợp hoàn hảo, để lại một dấu ấn sâu lắng, nam tính và đầy bí ẩn.', 'https://product.hstatic.net/1000340570/product/le-beau-for-men-mini-size--eau-de-toilette_966026420ae043d2a8f6cc264e2b200f_master.jpg', 35),

('Jean Paul Gaultier Le Male Le Parfum Mini Size', 4, 7, 7, 390000, N'Jean Paul Gaultier Le Male Le Parfum Mini Size là một hương thơm mạnh mẽ và quyến rũ, mang đến sự tự tin và phong cách cho người sử dụng. Phiên bản mini rất tiện lợi cho việc mang theo bên mình hoặc thử nghiệm mùi hương mà không cần mua chai lớn. Hương thơm mở đầu với sự tươi mát của bạch đậu khấu, tiếp đến là sự thanh lịch của hoa diên vĩ và oải hương, và cuối cùng là sự ấm áp, ngọt ngào của vanilla. Đây là một mùi hương đầy nam tính và cuốn hút, thể hiện sự mạnh mẽ và quyến rũ.', 'https://product.hstatic.net/1000340570/product/jean-paul-gaultier-le-male-le-parfum-mini-size--eau-de-parfum-intense-_dda0f8a5f7834a8097cf03f9cc3021c7_master.jpg', 35),

('Jean Paul Gaultier Scandal Pour Homme Mini Size', 4, 7, 7, 360000, N'Jean Paul Gaultier Scandal Pour Homme Mini Size là một hương thơm đầy năng lượng và lôi cuốn, lý tưởng cho những người đàn ông muốn tạo ấn tượng mạnh mẽ. Phiên bản mini rất tiện lợi cho việc mang theo hoặc thử nghiệm mùi hương. Hương thơm mở đầu với sự tươi mát của quýt và cây xô thơm, tiếp đến là sự ngọt ngào, hấp dẫn của caramel, và cuối cùng là sự ấm áp, nam tính của đậu tonka và cỏ hương bài. Đây là một mùi hương đầy sức sống và quyến rũ, hoàn hảo cho những dịp đặc biệt.', 'https://product.hstatic.net/1000340570/product/jean-paul-gaultier-scandal-pour-homme-mini-size_6c847adb32f245d68184e32b6bdd5d8a_master.jpg', 35),

    ('Versace Pour Homme', 1, 6, 6, 2400000, N'Versace Pour Homme là một hương nước hoa thanh lịch và nam tính, mở đầu với hương cam chanh tươi mát, kết hợp với hoa cam, hoa phong lữ và xạ hương. Hương giữa là sự pha trộn của gỗ tuyết tùng và hổ phách, tạo nên sự ấm áp và bền lâu. Cuối cùng, hương xạ hương và đậu tonka mang đến sự ngọt ngào và quyến rũ. Đây là lựa chọn hoàn hảo cho những dịp quan trọng hoặc khi bạn muốn cảm thấy tự tin và lịch lãm.', 'https://product.hstatic.net/1000340570/product/versace_pour_homme_b60616db384549e2baacb9f6b47a5bfc_master.jpg', 44),

    ('Versace Bright Crystal', 2, 6, 6, 3200000, N'Versace Bright Crystal là một hương nước hoa tươi mát và nữ tính với sự kết hợp của yuzu, lựu và hoa mẫu đơn. Hương giữa là hoa sen, hoa mộc lan và hoa nhài, tạo nên sự ngọt ngào và nữ tính. Cuối cùng, hương xạ hương và hổ phách mang đến sự ấm áp và bền lâu. Đây là lựa chọn lý tưởng cho những ngày hè hoặc khi bạn muốn cảm thấy tươi mới và sảng khoái.', 'https://product.hstatic.net/1000340570/product/versace-bright-crystal_405b9f59113d48dea5e79fd1dd3a99e9_master.jpg', 35),

    ('Versace Eros Pour Femme', 2, 6, 6, 2680000, N'Versace Eros Pour Femme là một hương nước hoa nữ tính, quyến rũ với sự kết hợp của hương chanh, lựu và cam bergamot. Hương giữa là sự hòa quyện của hoa nhài, hoa mẫu đơn và hoa cam, tạo nên sự ngọt ngào và nữ tính. Cuối cùng, hương xạ hương, hổ phách và gỗ đàn hương mang đến sự ấm áp và bền lâu. Đây là lựa chọn hoàn hảo cho những dịp đặc biệt hoặc khi bạn muốn cảm thấy tự tin và quyến rũ.', 'https://product.hstatic.net/1000340570/product/versace-eros-pour-femme-eau-de-parfum_f041c559b3c94e7b8eb661886fbd0bce_master.jpg', 35),

    ('Versace Oud Noir', 3, 6, 6, 2480000, N'Versace Oud Noir là một hương nước hoa sang trọng và quyến rũ với sự kết hợp của hương cam bergamot, cam và hoa cam. Hương giữa là sự pha trộn của gỗ oud mạnh mẽ và hổ phách, tạo nên sự ấm áp và bền lâu. Cuối cùng, hương xạ hương và vani mang đến sự ngọt ngào và quyến rũ. Đây là lựa chọn hoàn hảo cho cả nam và nữ, đặc biệt là trong những dịp đặc biệt hoặc khi bạn muốn cảm thấy sang trọng và quý phái.', 'https://product.hstatic.net/1000340570/product/versace-pour-homme-oud-noir-1_e88cfd50db5245a78ba73485670c314e_master.jpg', 30),

('Versace Pour Homme Mini Size', 1, 6, 6, 2400000, N'Versace Pour Homme là một hương nước hoa thanh lịch và nam tính, mở đầu với hương cam chanh tươi mát, kết hợp với hoa cam, hoa phong lữ và xạ hương. Hương giữa là sự pha trộn của gỗ tuyết tùng và hổ phách, tạo nên sự ấm áp và bền lâu. Cuối cùng, hương xạ hương và đậu tonka mang đến sự ngọt ngào và quyến rũ. Đây là lựa chọn hoàn hảo cho những dịp quan trọng hoặc khi bạn muốn cảm thấy tự tin và lịch lãm.', 'https://orchard.vn/wp-content/uploads/2024/09/versace-pour-homme-edt-mini-5ml_3.jpg.webp', 44),

    ('Versace Mini Bright Crystal Eau De Toilette Set', 4, 6, 6, 700000, N'Bộ sưu tập mini của Bright Crystal và Bright Crystal Absolu, tiện lợi cho việc mang theo khi du lịch. Đây là lựa chọn lý tưởng cho những ai muốn thử nghiệm các mùi hương khác nhau hoặc mang theo hương thơm yêu thích khi di chuyển.', 'https://product.hstatic.net/200000649197/product/thiet_ke_chua_co_ten__3__ac1e1e0365ed493cad8992cc36068edf.jpg', 20),

    ('Versace Mini Dylan Purple & Bright Crystal Perfume Set', 4, 6, 6, 800000, N'Bộ sưu tập mini của Dylan Purple và Bright Crystal, lý tưởng để thử nghiệm các mùi hương khác nhau. Những chai nước hoa này nhỏ gọn và dễ dàng mang theo bên mình, giúp bạn luôn tự tin với hương thơm yêu thích. Các chai mini này cũng rất tiện lợi để mang theo khi du lịch hoặc làm quà tặng.', 'https://glowskincaregt.com/cdn/shop/files/vewjshbjfsEIKJ.webp?v=1714698111', 10),

    ('Versace Miniature Trio Collection', 4, 6, 6, 800000, N'Bộ sưu tập gồm 3 chai mini của Yellow Diamond, Bright Crystal và Crystal Noir. Đây là lựa chọn hoàn hảo cho những ai muốn thử nhiều mùi hương khác nhau mà không cần mua chai lớn. Các chai mini này cũng rất tiện lợi để mang theo khi du lịch hoặc làm quà tặng. Các chai mini này cũng rất tiện lợi để mang theo khi du lịch hoặc làm quà tặng.', 'https://m.media-amazon.com/images/I/61ribvoQdJL._AC_UF1000,1000_QL80_.jpg', 10),

    ('Versace The Dreamer', 5, 6, 6, 1600000, N'Versace The Dreamer là một hương nước hoa độc đáo và lãng mạn, mở đầu với hương cây bách xù, ngải cứu và hoa lan Nam Phi. Tầng hương giữa là sự kết hợp của hoa diên vĩ, hoa lan và hoa hồng, tạo nên sự ngọt ngào và tinh tế. Cuối cùng, hương thuốc lá, hổ phách và đậu tonka mang đến sự ấm áp và bền lâu. Đây là lựa chọn hoàn hảo cho những ai yêu thích sự lãng mạn và muốn để lại ấn tượng khó quên.', 'https://bizweb.dktcdn.net/thumb/grande/100/103/974/products/nuoc-hoa-that-versace-dreamer-eau-de-toillete.jpg?v=1658125151243', 10),

    ('Versace Man Eau Fraiche', 5, 6, 6, 1710000, N'Versace Man Eau Fraîche là một hương nước hoa tươi mát và sảng khoái, hoàn hảo cho những ngày hè. Hương đầu mở ra với sự kết hợp của cam bergamot, chanh và quả carambola (quả khế), mang đến cảm giác tươi mới và sảng khoái. Hương giữa là sự pha trộn của táo xanh, calone và tiêu, tạo nên một tầng hương thanh mát và hơi cay nhẹ. Cuối cùng, hương gỗ tuyết tùng, hổ phách và xạ hương mang đến sự ấm áp và bền lâu.', 'https://product.hstatic.net/200000117693/product/309.8018365500037_850853c895494df6ab303028211dd337.jpg', 20),

    ('Tom Ford Velvet Orchid', 2, 8, 8, 3800000, N'Tom Ford Velvet Orchid là một hương nước hoa nữ tính và quyến rũ, mở đầu với hương cam bergamot, mật ong và rượu rum. Hương giữa là sự hòa quyện của hoa lan, hoa hồng và hoa nhài, tạo nên sự ngọt ngào và nữ tính. Cuối cùng, hương gỗ đàn hương, myrrh và vani mang đến sự ấm áp và bền lâu, để lại một dấu ấn khó quên.', 'https://product.hstatic.net/1000340570/product/tom-ford-velvet-orchid_d305972094c346f18ada3243d6a187a5_master.jpg', 15),

    ('Tom Ford Jasmin Rouge', 2, 8, 8, 5850000, N'Tom Ford Jasmin Rouge là một hương nước hoa gợi cảm và bí ẩn, với sự kết hợp của hoa nhài, ylang-ylang và cam bergamot. Hương giữa là sự hòa quyện của hương gỗ và gia vị, tạo nên một tầng hương đầy gợi cảm và quyến rũ. Cuối cùng, hương xạ hương và hổ phách mang đến sự ấm áp và bền lâu.', 'https://product.hstatic.net/1000340570/product/tom-ford-jasmin-rouge-edp-50ml_84bcf21b97ce4acf95cac15471b827f2_master.jpg', 15),

    ('Tom Ford Oud Wood', 1, 8, 8, 6950000, N'Tom Ford Oud Wood là một hương nước hoa sang trọng và quyến rũ, nổi bật với hương gỗ oud mạnh mẽ. Hương đầu mở ra với sự kết hợp của gỗ đàn hương, cỏ hương bài và hổ phách, tạo nên một mùi hương ấm áp và bền lâu. Đây là lựa chọn hoàn hảo cho những ai yêu thích sự sang trọng và muốn để lại ấn tượng khó quên.', 'https://product.hstatic.net/1000340570/product/tom-ford-oud-wood_71675d98e7fd4391b1e35401a82cef84_master.jpg', 30),

    ('Tom Ford Tobacco Vanille', 3, 8, 8, 7300000, N'Tom Ford Tobacco Vanille là một hương nước hoa ấm áp và ngọt ngào, với sự kết hợp của hương thuốc lá và vani. Hương đầu mở ra với sự pha trộn của cacao và đậu tonka, mang đến cảm giác ấm áp và quyến rũ. Cuối cùng, hương gỗ và hổ phách tạo nên một nền tảng bền lâu và gợi cảm.', 'https://clmensstore.com/wp-content/uploads/2021/05/Tom-Ford-Tobacco-Vanille-768x768.png', 30),

	('Tom Ford Neroli Portofino', 3, 8, 8, 5650000, N'Tom Ford Neroli Portofino là một hương nước hoa tươi mát và sảng khoái, với sự kết hợp của cam bergamot, cam và chanh. Hương giữa là sự hòa quyện của hoa cam, hoa nhài và hoa hồng, tạo nên một tầng hương tươi mát và thanh khiết. Cuối cùng, hương xạ hương và hổ phách mang đến sự ấm áp và bền lâu.', 'https://product.hstatic.net/1000340570/product/tom_ford_neroli_portofino_e41bf1144a08494f9cfe54dda3a936af_master.jpg', 20),

	('Tom Ford Private Blend Mini Discovery Set', 4, 8, 8, 5260000, N'Bộ sưu tập này gồm các chai mini 1.5ml của các mùi hương nổi tiếng như Lost Cherry, Tobacco Vanille, Soleil Blanc, Oud Wood và Rose Prick. Đây là lựa chọn hoàn hảo cho những ai muốn thử nhiều mùi hương khác nhau mà không cần mua chai lớn.', 'https://i.ebayimg.com/00/s/OTAwWDkwMA==/z/1dsAAOSwLA1nPPPs/$_3.JPG', 20),

	('Tom Ford Signature Mini Discovery Set', 4, 8, 8, 800000, N'Bộ sưu tập này gồm các chai mini 1.5ml của các mùi hương như Black Orchid, Noir Extreme, Ombré Leather, Eau de Soleil Blanc và Costa Azzurra. Những chai nước hoa này nhỏ gọn và dễ dàng mang theo bên mình, giúp bạn luôn tự tin với hương thơm yêu thích.', 'https://sdcdn.io/tf/tf_sku_TEY101_3000x3000_0.png?height=700px&options=BackgroundColor%3DF2F2F2&width=700px', 20),

	('Tom Ford Fucking Fabulous', 5, 8, 8, 6850000, N'Tom Ford Fucking Fabulous là một hương nước hoa độc đáo và gợi cảm, với sự kết hợp của hương da thuộc, hạnh nhân và đậu tonka. Hương đầu mở ra với sự pha trộn của vani và hổ phách, tạo nên một mùi hương ấm áp và bền lâu. Đây là lựa chọn hoàn hảo cho những dịp đặc biệt hoặc khi bạn muốn cảm thấy quyến rũ và bí ẩn.', 'https://product.hstatic.net/1000340570/product/tom-ford-fucking-fabulous-50ml_e56029a8261743789f02e96b8752d09a_master.jpg', 20),

	('Tom Ford Tuscan Leather', 5, 8, 8, 5550000, N'Tom Ford Tuscan Leather là một hương nước hoa sang trọng và quyến rũ, với sự kết hợp của hương da thuộc mạnh mẽ, quả mâm xôi và nghệ tây. Hương giữa là sự hòa quyện của hổ phách và gỗ, tạo nên một tầng hương ấm áp và bền lâu. Cuối cùng, hương xạ hương và vani mang đến sự ngọt ngào và quyến rũ.', 'https://xxivstore.com/wp-content/uploads/2020/06/3f2fbabb998b8b5a0467bb906cd65572-768x768.png', 20),

	('Tom Ford Soleil Blanc', 5, 8, 8, 5850000, N'Tom Ford Soleil Blanc là một hương nước hoa tươi mát và sang trọng, với sự kết hợp của cam bergamot, hoa cam và hoa nhài. Hương giữa là sự hòa quyện của hương dừa, hổ phách và vani, tạo nên một tầng hương tươi mát và thanh khiết. Cuối cùng, hương xạ hương và gỗ đàn hương mang đến sự ấm áp và bền lâu.', 'https://product.hstatic.net/1000340570/product/soleil-blanc-tom-ford_445224c94419407fb76076485d0eaf23_master.jpg', 20);

INSERT INTO roles (role_name) VALUES
	('ADMIN'),
	(N'USER');
GO

INSERT INTO discounts (discount_code, discount_percentage, max_discount_amount, start_date, end_date) VALUES
	('SALE10', 10, 500000, '2024-10-01', '2024-10-31'),
	('SALE30', 30, 700000, '2024-10-01', '2024-10-31'),
	('SALE5', 5, 100000, '2024-11-01', '2024-11-30'),
	('SALE40', 40, 1000000, '2024-11-01', '2024-11-30'),
	('SALE30', 30, 1000000, '2024-12-01', '2024-12-31');
GO

CREATE TRIGGER AddInvoiceAfterOrderInsert
ON orders
AFTER INSERT
AS
BEGIN
    -- Thêm dữ liệu vào bảng Invoices cho tất cả các dòng được chèn trong câu lệnh INSERT
    INSERT INTO invoices (orderid, invoice_date, total_amount, payment_method)
    SELECT 
        i.orderid,  -- Lấy OrderID từ bảng Orders
        GETDATE(),  -- Ngày giờ hiện tại khi tạo hóa đơn (thay vì OrderDate, vì InvoiceDate có thể là thời gian tạo hóa đơn)
        i.total_amount - 
            COALESCE(
                LEAST(
                    i.total_amount * d.discount_percentage / 100, 
                    d.max_discount_amount
                ), 
                0
            ) AS finalamout,  -- Tính số tiền sau khi giảm giá
        i.payment_method  -- Lấy PaymentMethod từ bảng Orders
    FROM Inserted i
    LEFT JOIN dbo.discounts d ON i.discountid = d.discountid;  -- Kết nối với bảng Discounts để lấy thông tin giảm giá
END;
GO


CREATE TRIGGER UpdatePaymentStatus
ON orders
AFTER UPDATE
AS
BEGIN
    -- Bắt đầu một transaction
    SET NOCOUNT ON;

    -- Cập nhật trạng thái thanh toán thành "đã thanh toán" nếu trạng thái giao hàng là "đã giao"
    UPDATE orders
    SET payment_status = N'Đã thanh toán'
    FROM orders o
    INNER JOIN Inserted i ON o.orderid = i.orderid
    WHERE i.delivery_status = N'Đã giao';
END;
GO
